<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="GEVW59D07RA24FU" name="com.zs.auto.day07_1029.login.LoginTest1" tests="1" failures="1" timestamp="30 Oct 2019 16:34:55 GMT" time="0.000" errors="0">
  <testcase name="case_test_success" time="0.000" classname="com.zs.auto.day07_1029.login.LoginTest1">
    <failure type="org.testng.TestNGException" message="
Method public void com.zs.auto.day07_1029.login.LoginTest1.case_test_success(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : data_success in class com.zs.auto.day07_1029.login.LoginDataProvider">
      <![CDATA[org.testng.TestNGException: 
Method public void com.zs.auto.day07_1029.login.LoginTest1.case_test_success(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException requires a @DataProvider named : data_success in class com.zs.auto.day07_1029.login.LoginDataProvider
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:268)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:417)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- case_test_success -->
</testsuite> <!-- com.zs.auto.day07_1029.login.LoginTest1 -->
